service: sls-poc-943-book

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2
  environment:
    DYNAMODB_TABLE: 'sls-poc-auth-943-books'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: book/create.create
    events:
      - http:
          path: book
          method: post
          cors: true

  list:
    handler: book/list.list
    events:
      - http:
          path: book
          method: get
          cors: true
        
  get:
    handler: book/get.get
    events:
      - http:
          path: book/{id}
          method: get
          cors: true
        
  update:
    handler: book/update.update
    events:
      - http:
          path: book/{id}
          method: put
          cors: true
  delete:
    handler: book/delete.delete
    events:
      - http:
          path: book/{id}
          method: delete
          cors: true        

resources:
  Resources:
    usersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
